# The following functions count_next() and count_start(), use the persistance
# functions to create an idiom where we have an increasing counter, that can be
# reset to 0 or set to a specific value. This is useful for example for
# iterating over files, for instance to review them after they were
# autogenerated.
def count_next ():
    i = store_get ('i', default=0)
    ex ('echo Using counter value: ' + str(i), echo=False)

    store ('i', i+1)

def count_start ():
    cli_counter = get_cli_arg_opt('--counter')
    val = 0
    if cli_counter != None:
        val = int(cli_counter)
    i = store ('i', val)
    ex ('echo Starting counter at: ' + str(i), echo=False)

if __name__ == "__main__":
    # Everything above this line will be executed for each TAB press.
    # If --get_completions is set, handle_tab_complete() calls exit().
    handle_tab_complete ()

    pymk_default()

